JAVA_HOME=/curr/diwu/tools/jdk
BOOST_DIR=/curr/diwu/tools/boost_1_55_0/install
PROTOBUF_DIR=/curr/diwu/tools/protobuf-2.5.0/build/install
HADOOP_DIR=/curr/diwu/tools/hadoop/hadoop-2.5.2
XILINX_OPENCL_DIR=/home/Xilinx/SDAccel_2015.1.3/SDAccel/2015.1

