JAVA_HOME=/curr/diwu/tools/jdk
BOOST_DIR=/curr/diwu/tools/boost_1_55_0/install
PROTOBUF_DIR=/curr/diwu/tools/protobuf-2.5.0/build/install
HADOOP_DIR=/curr/diwu/tools/hadoop/hadoop-2.5.2
MKL_DIR=/curr/diwu/intel_mkl
AAL_DIR=/curr/diwu/tools/aalsdk/4.1.7/aalsdk-4.1.7/build/install
XILINX_OPENCL_DIR=/space/Xilinx/SDAccel/2015.1
