JAVA_HOME=/home/ubuntu/tools/jdk
BOOST_DIR=/home/ubuntu/tools/boost_1_55_0/install
PROTOBUF_DIR=/home/ubuntu/tools/protobuf-2.5.0/build-static/install
HADOOP_DIR=/home/ubuntu/tools/hadoop/hadoop-2.5.2
GLOG_DIR=/home/ubuntu/tools/glog-0.3.3/build-ubuntu/install
CUDA_DIR=/usr/local/cuda
