// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package org.apache.spark.rddacc;

public final class AccMessage {
  private AccMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code rddacc.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACCREQUEST = 0;</code>
     */
    ACCREQUEST(0, 0),
    /**
     * <code>ACCGRANT = 1;</code>
     */
    ACCGRANT(1, 1),
    /**
     * <code>ACCREJECT = 2;</code>
     */
    ACCREJECT(2, 2),
    /**
     * <code>ACCFINISH = 3;</code>
     */
    ACCFINISH(3, 3),
    /**
     * <code>ACCDATA = 4;</code>
     */
    ACCDATA(4, 4),
    /**
     * <code>ACCFAILURE = 5;</code>
     */
    ACCFAILURE(5, 5),
    ;

    /**
     * <code>ACCREQUEST = 0;</code>
     */
    public static final int ACCREQUEST_VALUE = 0;
    /**
     * <code>ACCGRANT = 1;</code>
     */
    public static final int ACCGRANT_VALUE = 1;
    /**
     * <code>ACCREJECT = 2;</code>
     */
    public static final int ACCREJECT_VALUE = 2;
    /**
     * <code>ACCFINISH = 3;</code>
     */
    public static final int ACCFINISH_VALUE = 3;
    /**
     * <code>ACCDATA = 4;</code>
     */
    public static final int ACCDATA_VALUE = 4;
    /**
     * <code>ACCFAILURE = 5;</code>
     */
    public static final int ACCFAILURE_VALUE = 5;


    public final int getNumber() { return value; }

    public static MsgType valueOf(int value) {
      switch (value) {
        case 0: return ACCREQUEST;
        case 1: return ACCGRANT;
        case 2: return ACCREJECT;
        case 3: return ACCFINISH;
        case 4: return ACCDATA;
        case 5: return ACCFAILURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.apache.spark.rddacc.AccMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rddacc.MsgType)
  }

  public interface DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 partition_id = 1;
    /**
     * <code>required int32 partition_id = 1;</code>
     */
    boolean hasPartitionId();
    /**
     * <code>required int32 partition_id = 1;</code>
     */
    int getPartitionId();

    // required .rddacc.Data.DataType data_type = 2;
    /**
     * <code>required .rddacc.Data.DataType data_type = 2;</code>
     */
    boolean hasDataType();
    /**
     * <code>required .rddacc.Data.DataType data_type = 2;</code>
     */
    org.apache.spark.rddacc.AccMessage.Data.DataType getDataType();

    // required int64 size = 3;
    /**
     * <code>required int64 size = 3;</code>
     */
    boolean hasSize();
    /**
     * <code>required int64 size = 3;</code>
     */
    long getSize();

    // optional string path = 4;
    /**
     * <code>optional string path = 4;</code>
     */
    boolean hasPath();
    /**
     * <code>optional string path = 4;</code>
     */
    java.lang.String getPath();
    /**
     * <code>optional string path = 4;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * Protobuf type {@code rddacc.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage
      implements DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              partitionId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.apache.spark.rddacc.AccMessage.Data.DataType value = org.apache.spark.rddacc.AccMessage.Data.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                dataType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              path_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.spark.rddacc.AccMessage.Data.class, org.apache.spark.rddacc.AccMessage.Data.Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code rddacc.Data.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INT32 = 0;</code>
       */
      INT32(0, 0),
      /**
       * <code>UINT32 = 1;</code>
       */
      UINT32(1, 1),
      /**
       * <code>INT64 = 2;</code>
       */
      INT64(2, 2),
      /**
       * <code>UINT64 = 3;</code>
       */
      UINT64(3, 3),
      /**
       * <code>FLOAT = 4;</code>
       */
      FLOAT(4, 4),
      /**
       * <code>DOUBLE = 5;</code>
       */
      DOUBLE(5, 5),
      ;

      /**
       * <code>INT32 = 0;</code>
       */
      public static final int INT32_VALUE = 0;
      /**
       * <code>UINT32 = 1;</code>
       */
      public static final int UINT32_VALUE = 1;
      /**
       * <code>INT64 = 2;</code>
       */
      public static final int INT64_VALUE = 2;
      /**
       * <code>UINT64 = 3;</code>
       */
      public static final int UINT64_VALUE = 3;
      /**
       * <code>FLOAT = 4;</code>
       */
      public static final int FLOAT_VALUE = 4;
      /**
       * <code>DOUBLE = 5;</code>
       */
      public static final int DOUBLE_VALUE = 5;


      public final int getNumber() { return value; }

      public static DataType valueOf(int value) {
        switch (value) {
          case 0: return INT32;
          case 1: return UINT32;
          case 2: return INT64;
          case 3: return UINT64;
          case 4: return FLOAT;
          case 5: return DOUBLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.apache.spark.rddacc.AccMessage.Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private DataType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:rddacc.Data.DataType)
    }

    private int bitField0_;
    // required int32 partition_id = 1;
    public static final int PARTITION_ID_FIELD_NUMBER = 1;
    private int partitionId_;
    /**
     * <code>required int32 partition_id = 1;</code>
     */
    public boolean hasPartitionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 partition_id = 1;</code>
     */
    public int getPartitionId() {
      return partitionId_;
    }

    // required .rddacc.Data.DataType data_type = 2;
    public static final int DATA_TYPE_FIELD_NUMBER = 2;
    private org.apache.spark.rddacc.AccMessage.Data.DataType dataType_;
    /**
     * <code>required .rddacc.Data.DataType data_type = 2;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .rddacc.Data.DataType data_type = 2;</code>
     */
    public org.apache.spark.rddacc.AccMessage.Data.DataType getDataType() {
      return dataType_;
    }

    // required int64 size = 3;
    public static final int SIZE_FIELD_NUMBER = 3;
    private long size_;
    /**
     * <code>required int64 size = 3;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 size = 3;</code>
     */
    public long getSize() {
      return size_;
    }

    // optional string path = 4;
    public static final int PATH_FIELD_NUMBER = 4;
    private java.lang.Object path_;
    /**
     * <code>optional string path = 4;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string path = 4;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string path = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      partitionId_ = 0;
      dataType_ = org.apache.spark.rddacc.AccMessage.Data.DataType.INT32;
      size_ = 0L;
      path_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPartitionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, partitionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, dataType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, size_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPathBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, partitionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, dataType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, size_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPathBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.spark.rddacc.AccMessage.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.spark.rddacc.AccMessage.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rddacc.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.spark.rddacc.AccMessage.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.spark.rddacc.AccMessage.Data.class, org.apache.spark.rddacc.AccMessage.Data.Builder.class);
      }

      // Construct using org.apache.spark.rddacc.AccMessage.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        partitionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = org.apache.spark.rddacc.AccMessage.Data.DataType.INT32;
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_Data_descriptor;
      }

      public org.apache.spark.rddacc.AccMessage.Data getDefaultInstanceForType() {
        return org.apache.spark.rddacc.AccMessage.Data.getDefaultInstance();
      }

      public org.apache.spark.rddacc.AccMessage.Data build() {
        org.apache.spark.rddacc.AccMessage.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.spark.rddacc.AccMessage.Data buildPartial() {
        org.apache.spark.rddacc.AccMessage.Data result = new org.apache.spark.rddacc.AccMessage.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.partitionId_ = partitionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dataType_ = dataType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.spark.rddacc.AccMessage.Data) {
          return mergeFrom((org.apache.spark.rddacc.AccMessage.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.spark.rddacc.AccMessage.Data other) {
        if (other == org.apache.spark.rddacc.AccMessage.Data.getDefaultInstance()) return this;
        if (other.hasPartitionId()) {
          setPartitionId(other.getPartitionId());
        }
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000008;
          path_ = other.path_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPartitionId()) {
          
          return false;
        }
        if (!hasDataType()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.spark.rddacc.AccMessage.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.spark.rddacc.AccMessage.Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 partition_id = 1;
      private int partitionId_ ;
      /**
       * <code>required int32 partition_id = 1;</code>
       */
      public boolean hasPartitionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 partition_id = 1;</code>
       */
      public int getPartitionId() {
        return partitionId_;
      }
      /**
       * <code>required int32 partition_id = 1;</code>
       */
      public Builder setPartitionId(int value) {
        bitField0_ |= 0x00000001;
        partitionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 partition_id = 1;</code>
       */
      public Builder clearPartitionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        partitionId_ = 0;
        onChanged();
        return this;
      }

      // required .rddacc.Data.DataType data_type = 2;
      private org.apache.spark.rddacc.AccMessage.Data.DataType dataType_ = org.apache.spark.rddacc.AccMessage.Data.DataType.INT32;
      /**
       * <code>required .rddacc.Data.DataType data_type = 2;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .rddacc.Data.DataType data_type = 2;</code>
       */
      public org.apache.spark.rddacc.AccMessage.Data.DataType getDataType() {
        return dataType_;
      }
      /**
       * <code>required .rddacc.Data.DataType data_type = 2;</code>
       */
      public Builder setDataType(org.apache.spark.rddacc.AccMessage.Data.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .rddacc.Data.DataType data_type = 2;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataType_ = org.apache.spark.rddacc.AccMessage.Data.DataType.INT32;
        onChanged();
        return this;
      }

      // required int64 size = 3;
      private long size_ ;
      /**
       * <code>required int64 size = 3;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 size = 3;</code>
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>required int64 size = 3;</code>
       */
      public Builder setSize(long value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 size = 3;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0L;
        onChanged();
        return this;
      }

      // optional string path = 4;
      private java.lang.Object path_ = "";
      /**
       * <code>optional string path = 4;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string path = 4;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string path = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string path = 4;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 4;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000008);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 4;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rddacc.Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rddacc.Data)
  }

  public interface TaskMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .rddacc.MsgType type = 1;
    /**
     * <code>required .rddacc.MsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .rddacc.MsgType type = 1;</code>
     */
    org.apache.spark.rddacc.AccMessage.MsgType getType();

    // optional string acc_id = 2;
    /**
     * <code>optional string acc_id = 2;</code>
     */
    boolean hasAccId();
    /**
     * <code>optional string acc_id = 2;</code>
     */
    java.lang.String getAccId();
    /**
     * <code>optional string acc_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccIdBytes();

    // optional int32 task_id = 3;
    /**
     * <code>optional int32 task_id = 3;</code>
     */
    boolean hasTaskId();
    /**
     * <code>optional int32 task_id = 3;</code>
     */
    int getTaskId();

    // repeated .rddacc.Data data = 4;
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    java.util.List<org.apache.spark.rddacc.AccMessage.Data> 
        getDataList();
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    org.apache.spark.rddacc.AccMessage.Data getData(int index);
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    java.util.List<? extends org.apache.spark.rddacc.AccMessage.DataOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    org.apache.spark.rddacc.AccMessage.DataOrBuilder getDataOrBuilder(
        int index);

    // optional int32 get_data = 5;
    /**
     * <code>optional int32 get_data = 5;</code>
     */
    boolean hasGetData();
    /**
     * <code>optional int32 get_data = 5;</code>
     */
    int getGetData();
  }
  /**
   * Protobuf type {@code rddacc.TaskMsg}
   */
  public static final class TaskMsg extends
      com.google.protobuf.GeneratedMessage
      implements TaskMsgOrBuilder {
    // Use TaskMsg.newBuilder() to construct.
    private TaskMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaskMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaskMsg defaultInstance;
    public static TaskMsg getDefaultInstance() {
      return defaultInstance;
    }

    public TaskMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaskMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.apache.spark.rddacc.AccMessage.MsgType value = org.apache.spark.rddacc.AccMessage.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              taskId_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                data_ = new java.util.ArrayList<org.apache.spark.rddacc.AccMessage.Data>();
                mutable_bitField0_ |= 0x00000008;
              }
              data_.add(input.readMessage(org.apache.spark.rddacc.AccMessage.Data.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              getData_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_TaskMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_TaskMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.spark.rddacc.AccMessage.TaskMsg.class, org.apache.spark.rddacc.AccMessage.TaskMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<TaskMsg> PARSER =
        new com.google.protobuf.AbstractParser<TaskMsg>() {
      public TaskMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaskMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .rddacc.MsgType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.apache.spark.rddacc.AccMessage.MsgType type_;
    /**
     * <code>required .rddacc.MsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .rddacc.MsgType type = 1;</code>
     */
    public org.apache.spark.rddacc.AccMessage.MsgType getType() {
      return type_;
    }

    // optional string acc_id = 2;
    public static final int ACC_ID_FIELD_NUMBER = 2;
    private java.lang.Object accId_;
    /**
     * <code>optional string acc_id = 2;</code>
     */
    public boolean hasAccId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string acc_id = 2;</code>
     */
    public java.lang.String getAccId() {
      java.lang.Object ref = accId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string acc_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccIdBytes() {
      java.lang.Object ref = accId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 task_id = 3;
    public static final int TASK_ID_FIELD_NUMBER = 3;
    private int taskId_;
    /**
     * <code>optional int32 task_id = 3;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 task_id = 3;</code>
     */
    public int getTaskId() {
      return taskId_;
    }

    // repeated .rddacc.Data data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private java.util.List<org.apache.spark.rddacc.AccMessage.Data> data_;
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    public java.util.List<org.apache.spark.rddacc.AccMessage.Data> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    public java.util.List<? extends org.apache.spark.rddacc.AccMessage.DataOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    public org.apache.spark.rddacc.AccMessage.Data getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .rddacc.Data data = 4;</code>
     */
    public org.apache.spark.rddacc.AccMessage.DataOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    // optional int32 get_data = 5;
    public static final int GET_DATA_FIELD_NUMBER = 5;
    private int getData_;
    /**
     * <code>optional int32 get_data = 5;</code>
     */
    public boolean hasGetData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 get_data = 5;</code>
     */
    public int getGetData() {
      return getData_;
    }

    private void initFields() {
      type_ = org.apache.spark.rddacc.AccMessage.MsgType.ACCREQUEST;
      accId_ = "";
      taskId_ = 0;
      data_ = java.util.Collections.emptyList();
      getData_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, taskId_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(4, data_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, getData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, taskId_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, data_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.spark.rddacc.AccMessage.TaskMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.spark.rddacc.AccMessage.TaskMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rddacc.TaskMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.spark.rddacc.AccMessage.TaskMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_TaskMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_TaskMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.spark.rddacc.AccMessage.TaskMsg.class, org.apache.spark.rddacc.AccMessage.TaskMsg.Builder.class);
      }

      // Construct using org.apache.spark.rddacc.AccMessage.TaskMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.apache.spark.rddacc.AccMessage.MsgType.ACCREQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        accId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          dataBuilder_.clear();
        }
        getData_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.spark.rddacc.AccMessage.internal_static_rddacc_TaskMsg_descriptor;
      }

      public org.apache.spark.rddacc.AccMessage.TaskMsg getDefaultInstanceForType() {
        return org.apache.spark.rddacc.AccMessage.TaskMsg.getDefaultInstance();
      }

      public org.apache.spark.rddacc.AccMessage.TaskMsg build() {
        org.apache.spark.rddacc.AccMessage.TaskMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.spark.rddacc.AccMessage.TaskMsg buildPartial() {
        org.apache.spark.rddacc.AccMessage.TaskMsg result = new org.apache.spark.rddacc.AccMessage.TaskMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accId_ = accId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.taskId_ = taskId_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.getData_ = getData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.spark.rddacc.AccMessage.TaskMsg) {
          return mergeFrom((org.apache.spark.rddacc.AccMessage.TaskMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.spark.rddacc.AccMessage.TaskMsg other) {
        if (other == org.apache.spark.rddacc.AccMessage.TaskMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAccId()) {
          bitField0_ |= 0x00000002;
          accId_ = other.accId_;
          onChanged();
        }
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000008);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        if (other.hasGetData()) {
          setGetData(other.getGetData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.spark.rddacc.AccMessage.TaskMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.spark.rddacc.AccMessage.TaskMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .rddacc.MsgType type = 1;
      private org.apache.spark.rddacc.AccMessage.MsgType type_ = org.apache.spark.rddacc.AccMessage.MsgType.ACCREQUEST;
      /**
       * <code>required .rddacc.MsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .rddacc.MsgType type = 1;</code>
       */
      public org.apache.spark.rddacc.AccMessage.MsgType getType() {
        return type_;
      }
      /**
       * <code>required .rddacc.MsgType type = 1;</code>
       */
      public Builder setType(org.apache.spark.rddacc.AccMessage.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .rddacc.MsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.apache.spark.rddacc.AccMessage.MsgType.ACCREQUEST;
        onChanged();
        return this;
      }

      // optional string acc_id = 2;
      private java.lang.Object accId_ = "";
      /**
       * <code>optional string acc_id = 2;</code>
       */
      public boolean hasAccId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string acc_id = 2;</code>
       */
      public java.lang.String getAccId() {
        java.lang.Object ref = accId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string acc_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccIdBytes() {
        java.lang.Object ref = accId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string acc_id = 2;</code>
       */
      public Builder setAccId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string acc_id = 2;</code>
       */
      public Builder clearAccId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accId_ = getDefaultInstance().getAccId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string acc_id = 2;</code>
       */
      public Builder setAccIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accId_ = value;
        onChanged();
        return this;
      }

      // optional int32 task_id = 3;
      private int taskId_ ;
      /**
       * <code>optional int32 task_id = 3;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 task_id = 3;</code>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>optional int32 task_id = 3;</code>
       */
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000004;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 task_id = 3;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        taskId_ = 0;
        onChanged();
        return this;
      }

      // repeated .rddacc.Data data = 4;
      private java.util.List<org.apache.spark.rddacc.AccMessage.Data> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = new java.util.ArrayList<org.apache.spark.rddacc.AccMessage.Data>(data_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.spark.rddacc.AccMessage.Data, org.apache.spark.rddacc.AccMessage.Data.Builder, org.apache.spark.rddacc.AccMessage.DataOrBuilder> dataBuilder_;

      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public java.util.List<org.apache.spark.rddacc.AccMessage.Data> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public org.apache.spark.rddacc.AccMessage.Data getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder setData(
          int index, org.apache.spark.rddacc.AccMessage.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder setData(
          int index, org.apache.spark.rddacc.AccMessage.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder addData(org.apache.spark.rddacc.AccMessage.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder addData(
          int index, org.apache.spark.rddacc.AccMessage.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder addData(
          org.apache.spark.rddacc.AccMessage.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder addData(
          int index, org.apache.spark.rddacc.AccMessage.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends org.apache.spark.rddacc.AccMessage.Data> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public org.apache.spark.rddacc.AccMessage.Data.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public org.apache.spark.rddacc.AccMessage.DataOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public java.util.List<? extends org.apache.spark.rddacc.AccMessage.DataOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public org.apache.spark.rddacc.AccMessage.Data.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            org.apache.spark.rddacc.AccMessage.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public org.apache.spark.rddacc.AccMessage.Data.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, org.apache.spark.rddacc.AccMessage.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .rddacc.Data data = 4;</code>
       */
      public java.util.List<org.apache.spark.rddacc.AccMessage.Data.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.spark.rddacc.AccMessage.Data, org.apache.spark.rddacc.AccMessage.Data.Builder, org.apache.spark.rddacc.AccMessage.DataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.spark.rddacc.AccMessage.Data, org.apache.spark.rddacc.AccMessage.Data.Builder, org.apache.spark.rddacc.AccMessage.DataOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // optional int32 get_data = 5;
      private int getData_ ;
      /**
       * <code>optional int32 get_data = 5;</code>
       */
      public boolean hasGetData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 get_data = 5;</code>
       */
      public int getGetData() {
        return getData_;
      }
      /**
       * <code>optional int32 get_data = 5;</code>
       */
      public Builder setGetData(int value) {
        bitField0_ |= 0x00000010;
        getData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 get_data = 5;</code>
       */
      public Builder clearGetData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        getData_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rddacc.TaskMsg)
    }

    static {
      defaultInstance = new TaskMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rddacc.TaskMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rddacc_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rddacc_Data_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rddacc_TaskMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rddacc_TaskMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntask.proto\022\006rddacc\"\263\001\n\004Data\022\024\n\014partiti" +
      "on_id\030\001 \002(\005\022(\n\tdata_type\030\002 \002(\0162\025.rddacc." +
      "Data.DataType\022\014\n\004size\030\003 \002(\003\022\014\n\004path\030\004 \001(" +
      "\t\"O\n\010DataType\022\t\n\005INT32\020\000\022\n\n\006UINT32\020\001\022\t\n\005" +
      "INT64\020\002\022\n\n\006UINT64\020\003\022\t\n\005FLOAT\020\004\022\n\n\006DOUBLE" +
      "\020\005\"w\n\007TaskMsg\022\035\n\004type\030\001 \002(\0162\017.rddacc.Msg" +
      "Type\022\016\n\006acc_id\030\002 \001(\t\022\017\n\007task_id\030\003 \001(\005\022\032\n" +
      "\004data\030\004 \003(\0132\014.rddacc.Data\022\020\n\010get_data\030\005 " +
      "\001(\005*b\n\007MsgType\022\016\n\nACCREQUEST\020\000\022\014\n\010ACCGRA" +
      "NT\020\001\022\r\n\tACCREJECT\020\002\022\r\n\tACCFINISH\020\003\022\013\n\007AC",
      "CDATA\020\004\022\016\n\nACCFAILURE\020\005B%\n\027org.apache.sp" +
      "ark.rddaccB\nAccMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rddacc_Data_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rddacc_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rddacc_Data_descriptor,
              new java.lang.String[] { "PartitionId", "DataType", "Size", "Path", });
          internal_static_rddacc_TaskMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rddacc_TaskMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rddacc_TaskMsg_descriptor,
              new java.lang.String[] { "Type", "AccId", "TaskId", "Data", "GetData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
